Simple Turning Machine, from srcatch

In [1]:
import numpy as np
import sys
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (10,6)

Input Tape, array of 1 and 0's

In [2]:
tape = np.array([0,1,1,1,1,0])
print (tape)

[0 1 1 1 1 0]


Create 'state' of the machine, it can be 'start' , 'even', 'odd', 'halt'

In [3]:
state = 'start'
print (state)

start


Rule 1, if in 'start' state and read a '0' the change state to 'even', delete the cell

In [4]:
def Rule_One(state, tape):
    if state == 'start':
        if tape[0] == 0:
            state = 'even'
            tape = np.delete(tape, [0])
    return state, tape
    


In [5]:
state, tape = Rule_One(state, tape)
print (state)
print (tape)

even
[1 1 1 1 0]


|Rule 2: If in 'even' state and read a 1 then change to 'odd' state, delete the cell

In [6]:
#debug forced options
#state = 'odd'
#state = 'even'

In [7]:
def Rule_Two(state, tape):
    if state == 'even':
        if tape[0] == 1:
            state = 'odd'
            tape = np.delete(tape, [0])
    return state, tape

In [8]:
state, tape = Rule_Two(state, tape)
print (state)
print (tape)

odd
[1 1 1 0]


Rule 3:If in 'odd' state and read '1' then state = 'even'

In [9]:
def Rule_Three(state, tape):
    if state == 'odd':
        if tape[0] == 1:
            state = 'even'
            answer = 'even'
            tape = np.delete(tape, [0])
    return state, tape

In [10]:
state, tape = Rule_Three(state, tape)
print(state)
print (tape)

even
[1 1 0]


Rule 4:If in 'odd' state and read '0' then state = 'halt'

In [11]:
#debug forced options
#tape = np.array([0,1,1,1,1,0])
state = 'odd'
#state = 'even'

In [12]:
def Rule_Four(state, tape):
    answer = ''
    if state == 'odd':
        if tape[0] == 0:
            state, answer = 'halt', 'ODD'  
    return state, tape, answer

In [13]:
state, tape, answer = Rule_Four(state, tape)
print (answer)

Rule 5:If in 'even' state and read '0' then state = 'halt'

In [14]:
#debug forced options
#state = 'odd'
state = 'even'

In [15]:
def Rule_Five(state, tape, answer):
    if state == 'even':
        if tape[0] == 0:
            state, answer = 'halt', 'EVEN'
    return state, tape, answer

In [16]:
state, tape, answer = Rule_Five(state, tape, answer)
print (answer)


Running the Turning Machine on the input. Now bring it all together, apply all the rules on the tape

In [17]:
#debug forced options
#state = 'odd'
#state = 'even'
#state = 'start'
#tape = np.array([0,1,1,1,1,0])

Reset the Machine

In [26]:
state = 'start'
tape = np.array([0,1,1,1,0])
answer = 'not_sure'

In [27]:
print ('The Input state = ', state)
print ('The Input tape', tape)


while True:
    state, tape = Rule_One(state, tape)
    print ('Rule 1 completed, State =', state, '  Tape = ', tape)


    state, tape = Rule_Two(state, tape)
    print ('Rule 2 completed, State =', state, '  Tape = ', tape)
 
        
    state, tape = Rule_Three(state, tape)
    print ('Rule 3 completed, State =', state, '  Tape = ', tape)
 

    state, tape, answer = Rule_Four(state, tape)
    print ('Rule 4 completed, State =', state, '  Tape = ', tape)
  
        
    state, tape, answer = Rule_Five(state, tape, answer)
    print ('Rule 5 completed, State =', state, '  Tape = ', tape)
    

    
    if state == 'halt':
        break

print ('The Output State is = ', state )

print ('And the answer is ...', answer)
           
    


      

The Input state =  start
The Input tape [0 1 1 1 0]
Rule 1 completed, State = even   Tape =  [1 1 1 0]
Rule 2 completed, State = odd   Tape =  [1 1 0]
Rule 3 completed, State = even   Tape =  [1 0]
Rule 4 completed, State = even   Tape =  [1 0]
Rule 5 completed, State = even   Tape =  [1 0]
Rule 1 completed, State = even   Tape =  [1 0]
Rule 2 completed, State = odd   Tape =  [0]
Rule 3 completed, State = odd   Tape =  [0]
Rule 4 completed, State = halt   Tape =  [0]
Rule 5 completed, State = halt   Tape =  [0]
The Output State is =  halt
And the answer is ... ODD


In [28]:
print ('The Output State is = ', state )

print ('And the answer is ...', answer)

The Output State is =  halt
And the answer is ... ODD
